#!/usr/bin/env bash
# Web servers are the piece of software generating and serving HTML pages, let’s install one!
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.html
service nginx start
