#!/usr/bin/env bash
# Web servers are the piece of software generating and serving HTML pages, let’s install one!
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.html

mkdir /var/www/error

printf %s "Ceci n'est pas une page
" > /var/www/error/error_40x.html;


printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /var/www/html;
    index  index.html index.htm;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    error_page 404 /error_40x.html;
    location = /error_40x.html {
        root /var/www/error;
        internal;
    }
}" > /etc/nginx/sites-available/default

if [ "$(pgrep -c nginx)" -gt 0 ];
then
    service nginx restart
else
    service nginx start
fi

