#!/usr/bin/env bash
# print Best School 10 times


while IFS=: read -r user gang city ride name passcode url
do
  echo "The user $user is part of the $name gang, lives in $passcode and rides $gang. $url's place is protected by the passcode $city, more info about the user here: $ride"
done < "/etc/passwd"

