#!/usr/bin/env bash
# print Best School 10 times


while IFS=: read -r user gang city ride name passcode url
do
  echo "The user $user is part of the $gang gang, lives in $city and rides $ride. $name's place is protected by the passcode $passcode, more info about the user here: $url"
done < "/etc/passwd"
